mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'
urlpatterns = [

    # the name value is called by the {% url %} template tag
    path('', views.homeview, name='home'),
    path('projects/', views.ProjectView.as_view(), name='project'),
    path('experiences/', views.ExperView.as_view(), name='exper'),
    path('blog/', views.BlogView.as_view(), name='blog'),

]

mysite/portfolio/models.py
import os

from django.db import models


# Create your models here.
class TextBubble(models.Model):
    TAG = (
        ('P', 'Project'),
        ('E', 'Experience'),
        ('I', 'Blog'),
    )
    name = models.CharField(max_length=200)
    tag = models.CharField(max_length=1, choices=TAG)
    pub_date = models.DateTimeField('date_published')
    text = models.TextField()
    picture = models.ImageField(upload_to='images/')
    links = models.URLField(max_length=1000, blank=True)

    def __str__(self):
        return self.name


class Resume(models.Model):
    pdf_link = models.FileField(upload_to='uploads/', max_length=100)
    pdf_name = models.CharField(max_length=200)

    def __str__(self):
        return self.pdf_name


class Quotes(models.Model):
    quote = models.CharField(max_length=800)
    author = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.quote


class Languages(models.Model):
    language_link = models.ForeignKey(TextBubble, on_delete=models.CASCADE, related_name='llink')
    languages = models.CharField(max_length=100, blank=True)

mysite/portfolio/views.py
from django.views import generic
from django.http import HttpResponse
from django.template import loader
from .models import TextBubble, Resume, Quotes


# Create your views here.

def homeview(request):
    template = loader.get_template('portfolio/home.html')
    resume = Resume.objects.all()
    quotes = Quotes.objects.all()
    context = {
        'resume': resume, 'quotes': quotes.order_by('-pub_date'),
    }
    return HttpResponse(template.render(context, request))


class ProjectView(generic.ListView):
    model = TextBubble
    template_name = 'portfolio/projects.html'

    def get_queryset(self):
        """
        includes all project types
        """
        return TextBubble.objects.filter(tag__startswith='P').order_by('-pub_date')


class ExperView(generic.ListView):
    model = TextBubble
    template_name = 'portfolio/exper.html'

    def get_queryset(self):
        """
        includes all experiance types
        """
        return TextBubble.objects.filter(tag__startswith='E').order_by('-pub_date')


class BlogView(generic.ListView):
    model = TextBubble
    template_name = 'portfolio/blog.html'

    def get_queryset(self):
        """
        includes all interests types
        """
        return TextBubble.objects.filter(tag__startswith='I').order_by('-pub_date')

mysite/portfolio/templates/portfolio/blog.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Blog</title>
</head>
<body>
<div class="container-fluid" style="z-index: 0">
    <div class="d-flex flex-column" style="z-index: 1">
        <a name="top"></a>
        <div class="navbar-container">
                <nav class="navbar">
                    <h5 class="nb">
                        <ul>
                            <li class="n"><a href="{% url 'portfolio:home' %}">/Home</a></li>
                            <li class="n"><a href="{% url 'portfolio:project' %}">/Projects</a></li>
                            <li class="n"><a href="{% url 'portfolio:exper' %}">/Experiences</a></li>
                            <li class="n"><a class="active" href="{% url 'portfolio:blog' %}">/Blog</a></li>
                        </ul>
                    </h5>
                </nav>
            </div>
        <div class="p-2" style="z-index: 3;">
            <h1 class="type4" style="font-size: 72px;">> Blog</h1>
        </div>
        <div class="p-2" style="z-index: 3; margin-top: 48px;">
            <ul>
                {% for TextBubble in object_list %}
                <div class="bubble"style="width: 100%;
                        max-width: 1000px;
                        height: 400px;
                        border-radius: 5px;
                        box-shadow: 0 4px 8px 0 rgb(209, 209, 214), 0 6px 20px 0 rgb(209, 209, 214) ;
                        background: rgb(242, 242, 247)">
                    <div class="pix"
                         style="width: 40%;
                                max-width: 800px;
                                height: 400px;
                                float: left;
                                border-radius: 5px;
                                box-shadow: 0 4px 8px 0 rgb(209, 209, 214), 0 6px 20px 0 rgb(209, 209, 214)
                                background: rgb(242, 242, 247)">
                    <img class="pics"src="{{ TextBubble.picture.url }}" alt="{{TextBubble.name}}">
                    </div>
                    <div class="words"
                         style="width: 60%;
                                max-width: 800px;
                                height: 400px;
                                float: right;
                                border-radius: 0px 5px 5px 0px;
                                border-left:5px solid rgb(209,209,214);
                                background: rgb(242, 242, 247)">
                        <h2 class="bTitle">
                            <svg class="bi bi-heart-half" style="color: #5ca2d5;" width="2em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M8 1.314C3.562-3.248-7.534 4.735 8 15V1.314z" clip-rule="evenodd"/>
                                <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 01.176-.17C12.72-3.042 23.333 4.867 8 15z" clip-rule="evenodd"/>
                            </svg>
                            {{TextBubble.name}}
                        </h2>
                        <h6 class="bDate">{{TextBubble.pub_date}}</h6>
                        <h6 class="bText" style="color: rgb(72,72,74);">{{TextBubble.text}}</h6>
                        <h6 class="bLink">Link: <a class="bLink-L"href="{{TextBubble.links}}"target="_new">
                            <svg class="bi bi-link-45deg" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M4.715 6.542L3.343 7.914a3 3 0 104.243 4.243l1.828-1.829A3 3 0 008.586 5.5L8 6.086a1.001 1.001 0 00-.154.199 2 2 0 01.861 3.337L6.88 11.45a2 2 0 11-2.83-2.83l.793-.792a4.018 4.018 0 01-.128-1.287z"/>
                                <path d="M5.712 6.96l.167-.167a1.99 1.99 0 01.896-.518 1.99 1.99 0 01.518-.896l.167-.167A3.004 3.004 0 006 5.499c-.22.46-.316.963-.288 1.46z"/>
                                <path d="M6.586 4.672A3 3 0 007.414 9.5l.775-.776a2 2 0 01-.896-3.346L9.12 3.55a2 2 0 012.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 00-4.243-4.243L6.586 4.672z"/>
                                <path d="M10 9.5a2.99 2.99 0 00.288-1.46l-.167.167a1.99 1.99 0 01-.896.518 1.99 1.99 0 01-.518.896l-.167.167A3.004 3.004 0 0010 9.501z"/>
                            </svg>
                        </a></h6>
                    </div>
                </div>
                <div class="space" style="height: 60px">
                </div>
                {% endfor %}
            </ul>
            <h3><a href="#top" class="top">Back to Top</a></h3>
        </div>
    </div>
</div>

</body>
</html>

mysite/portfolio/templates/portfolio/exper.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Experiences</title>
</head>
<body>
<div class="container-fluid" style="z-index: 0">
    <div class="d-flex flex-column" style="z-index: 1">
        <a name="top"></a>
        <div class="navbar-container">
                <nav class="navbar">
                    <h5 class="nb">
                        <ul>
                            <li class="n"><a href="{% url 'portfolio:home' %}">/Home</a></li>
                            <li class="n"><a href="{% url 'portfolio:project' %}">/Projects</a></li>
                            <li class="n"><a class="active" href="{% url 'portfolio:exper' %}">/Experiences</a></li>
                            <li class="n"><a href="{% url 'portfolio:blog' %}">/Blog</a></li>
                        </ul>
                    </h5>
                </nav>
            </div>
         <div class="p-2" style="z-index: 3;">
            <h1 class="type3" style="font-size: 72px;">> Experiences</h1>
        </div>
        <div class="p-2" style="z-index: 3; margin-top: 48px;">
            <ul>
                {% for TextBubble in object_list %}
                <div class="bubble"style="width: 100%;
                        max-width: 1000px;
                        height: 400px;
                        border-radius: 5px;
                        box-shadow: 0 4px 8px 0 rgb(209, 209, 214), 0 6px 20px 0 rgb(209, 209, 214) ;
                        background: rgb(242, 242, 247)">
                    <div class="pix"
                         style="width: 40%;
                                max-width: 800px;
                                height: 400px;
                                float: left;
                                border-radius: 5px;
                                box-shadow: 0 4px 8px 0 rgb(209, 209, 214), 0 6px 20px 0 rgb(209, 209, 214)
                                background: rgb(242, 242, 247)">
                    <img class="pics"src="{{ TextBubble.picture.url }}" alt="{{TextBubble.name}}">
                    </div>
                    <div class="words"
                         style="width: 60%;
                                max-width: 800px;
                                height: 400px;
                                float: right;
                                border-radius: 0px 5px 5px 0px;
                                border-left:5px solid rgb(209,209,214);
                                background: rgb(242, 242, 247)">
                        <h2 class="bTitle">
                            <svg class="bi bi-people-fill" style="color: #5ca2d5" width="2em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 100-6 3 3 0 000 6zm-5.784 6A2.238 2.238 0 015 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 005 9c-4 0-5 3-5 4s1 1 1 1h4.216zM4.5 8a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" clip-rule="evenodd"/>
                            </svg>
                            {{TextBubble.name}}
                        </h2>
                        <h6 class="bDate">{{TextBubble.pub_date}}</h6>
                        <h6 class="bText" style="color: rgb(72,72,74);">{{TextBubble.text}}</h6>
                        <ul class="lan" style="height: 10%; margin: 0 auto; float: bottom">
                            {% for Languages in TextBubble.llink.all %}
                            <li class="l">
                                <h6 class="lang" style="color: #f68887;">
                                    <svg class="bi bi-file-code" style="color: rgb(99, 99, 102);"width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M4 1h8a2 2 0 012 2v10a2 2 0 01-2 2H4a2 2 0 01-2-2V3a2 2 0 012-2zm0 1a1 1 0 00-1 1v10a1 1 0 001 1h8a1 1 0 001-1V3a1 1 0 00-1-1H4z" clip-rule="evenodd"/>
                                        <path fill-rule="evenodd" d="M8.646 5.646a.5.5 0 01.708 0l2 2a.5.5 0 010 .708l-2 2a.5.5 0 01-.708-.708L10.293 8 8.646 6.354a.5.5 0 010-.708zm-1.292 0a.5.5 0 00-.708 0l-2 2a.5.5 0 000 .708l2 2a.5.5 0 00.708-.708L5.707 8l1.647-1.646a.5.5 0 000-.708z" clip-rule="evenodd"/>
                                    </svg>
                                    {{Languages.languages}}</h6>
                            </li>
                            {% endfor %}
                        </ul>
                       </div>
                </div>
                <div class="space" style="height: 60px">
                </div>
                {% endfor %}
            </ul>
            <h3><a href="#top" class="top">Back to Top</a></h3>
        </div>
    </div>
</div>

</body>
</html>

mysite/portfolio/templates/portfolio/home.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home</title>
</head>
<body>
<div class="container-fluid" style="z-index: 0">
    <div class="d-flex flex-column" style="z-index: 1">
        <a name="top"></a>
        <div class="navbar-container">
                <nav class="navbar">
                    <h5 class="nb">
                        <ul>
                            <li class="n"><a class="active"href="{% url 'portfolio:home' %}">/Home</a></li>
                            <li class="n"><a href="{% url 'portfolio:project' %}">/Projects</a></li>
                            <li class="n"><a href="{% url 'portfolio:exper' %}">/Experiences</a></li>
                            <li class="n"><a href="{% url 'portfolio:blog' %}">/Blog</a></li>
                        </ul>
                    </h5>
                </nav>
            </div>
        <div class="p-2" style="z-index: 3;">
            <h1 class="type" style="font-size: 72px;">> Drasti Mehta</h1>
        </div>
        <div class="p-2" style="z-index: 4; height: 150%; margin-top: 50px">
            <div id="outer-rec"
                 style="width: 100%;
                        max-width: 800px;
                        height: 450px;
                        z-index: 5;
                        border-radius: 5px;
                        box-shadow: 4px 4px 20px 4px #ccc;
                        background: rgb(72, 72, 74)">
                <h2 style="margin-left: 15px; ">
                    <span class="dot1"
                          style="
                          position: relative;
                          height: 15px;
                          width:15px;
                          background-color: rgb(255, 69, 58);
                          border-radius: 50%;
                          box-shadow: inset 0 0 10px rgb(265, 79, 58);
                          display: inline-block;"></span>
                    <span class="dot2"
                          style="
                          position: relative;
                          height: 15px;
                          width:15px;
                          background-color: rgb(255, 214, 10);
                          border-radius: 50%;
                          box-shadow: inset 0 0 10px rgb(265, 224, 10);
                          display: inline-block;"></span>
                    <span class="dot3"
                          style="
                          position: relative;
                          height: 15px;
                          width:15px;
                          background-color: rgb(60, 215, 75);
                          box-shadow: inset 0 0 10px rgb(50, 225, 75);
                          border-radius: 50%;
                          display: inline-block;"></span>

                </h2>
                <div id="inner-rec"
                    style="width: 100%;
                           height: 100%;
                           border-radius: 0px 0px 5px 5px;
                           margin: auto;
                           z-index: 6;
                           box-shadow: 4px 4px 8px 0px #ccc;
                           background: rgb(99, 99, 102)">
                    <div style="padding-left: 40px; padding-top: 30px; padding-bottom: 30px;">
                        <h6 class="white">> Drasti.greeting<br></h6>
                        <h6 class="color">"Hello, I hope you enjoy exploring my website. Check out my projects, experiences, and blog!"<br><br></h6>
                        <h6 class="white">> Drasti.education<br></h6>
                        <h6 class="color">"Honours Computer Engineering ('24) - University of Waterloo"<br><br></h6>
                        <h6 class="white">> Drasti.resume<br></h6>
                        <h6 class="color">
                            {% for Resume in resume %}
                            <a href="{{Resume.pdf_link.url}}" target="_new" class="link">"drastimehta.pdf"</a>
                            {% endfor %}
                        <br><br></h6>
                        <h6 class="white">> Drasti.interests<br></h6>
                        <h6 class="color">["music", "space exploration", "fashion", "horror movies"]<br><br></h6>
                        <h6 class="white">> Drasti.contact<br></h6>
                        <h6 class="color">["<a href="mailto:d36mehta@uwaterloo.ca" target="_new" class="link">d36mehta@uwaterloo.ca</a>",
                            "<a href="https://www.linkedin.com/in/drasti-mehta/" target="_new" class="link">linkedin</a>",
                            "<a href="https://twitter.com/drastimehta" target="_new" class="link">twitter</a>",
                            "<a href="https://github.com/d36mehta" target="_new" class="link">github</a>"]<br><br></h6>
                        <h6 class="white">> Drasti.goodBye<br></h6>
                        <h6 class="color">"Scroll down to enjoy some nice quotes. Have a nice day!!"<br><br></h6>
                        <h6 class="white typewriter">></h6>
                    </div>
                </div>
         </div>
        </div>
         <div class="p-2">
             <div class="qu" style="padding-top: 120px;">
                 <h2 class="quo-icon">
                     <svg class="bi bi-chat-square-quote-fill" width="8em" height="6em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                         <path fill-rule="evenodd" d="M0 2a2 2 0 012-2h12a2 2 0 012 2v8a2 2 0 01-2 2h-2.5a1 1 0 00-.8.4l-1.9 2.533a1 1 0 01-1.6 0L5.3 12.4a1 1 0 00-.8-.4H2a2 2 0 01-2-2V2zm7.194 2.766c.087.124.163.26.227.401.428.948.393 2.377-.942 3.706a.446.446 0 01-.612.01.405.405 0 01-.011-.59c.419-.416.672-.831.809-1.22-.269.165-.588.26-.93.26C4.775 7.333 4 6.587 4 5.667 4 4.747 4.776 4 5.734 4c.271 0 .528.06.756.166l.008.004c.169.07.327.182.469.324.085.083.161.174.227.272zM11 7.073c-.269.165-.588.26-.93.26-.958 0-1.735-.746-1.735-1.666 0-.92.777-1.667 1.734-1.667.271 0 .528.06.756.166l.008.004c.17.07.327.182.469.324.085.083.161.174.227.272.087.124.164.26.228.401.428.948.392 2.377-.942 3.706a.446.446 0 01-.613.01.405.405 0 01-.011-.59c.42-.416.672-.831.81-1.22z" clip-rule="evenodd"/>
                     </svg>
                 </h2>
                 <ul class="quote" style="padding-top: 25px;">
                     {% for Quotes in quotes %}
                     <h1 class="bigBL">{</h1>
                     <br>
                     <h3 class="quote-text">{{Quotes.quote}}</h3><br>
                     <h5 class="quote-author">> {{Quotes.author}}</h5>
                     <br>
                     <h1 class="bigBR">}</h1>
                     {% endfor %}
                 </ul>
                 <h3><a href="#top" class="top">Back to Top</a></h3>
             </div>
        </div>

    </div>
</div>

</body>
</html>

mysite/portfolio/templates/portfolio/main_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mysite/portfolio/templates/portfolio/projects.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'portfolio/style.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Projects</title>
</head>
<body>
<div class="container-fluid" style="z-index: 0">
    <div class="d-flex flex-column" style="z-index: 1">
        <a name="top"></a>
        <div class="navbar-container">
                <nav class="navbar">
                    <h5 class="nb">
                        <ul>
                            <li class="n"><a href="{% url 'portfolio:home' %}">/Home</a></li>
                            <li class="n"><a class="active" href="{% url 'portfolio:project' %}">/Projects</a></li>
                            <li class="n"><a href="{% url 'portfolio:exper' %}">/Experiences</a></li>
                            <li class="n"><a href="{% url 'portfolio:blog' %}">/Blog</a></li>
                        </ul>
                    </h5>
                </nav>
            </div>
        <div class="p-2" style="z-index: 3;">
            <h1 class="type2" style="font-size: 72px;">> Projects</h1>
        </div>
        <div class="p-2" style="z-index: 3; margin-top: 48px;">
            <ul>
                {% for TextBubble in object_list %}
                <div class="bubble"style="width: 100%;
                        max-width: 1000px;
                        height: 400px;
                        border-radius: 5px;
                        box-shadow: 0 4px 8px 0 rgb(209, 209, 214), 0 6px 20px 0 rgb(209, 209, 214) ;
                        background: rgb(242, 242, 247)">
                    <div class="pix"
                         style="width: 40%;
                                max-width: 800px;
                                height: 400px;
                                float: left;
                                border-radius: 5px;
                                box-shadow: 0 4px 8px 0 rgb(209, 209, 214), 0 6px 20px 0 rgb(209, 209, 214)
                                background: rgb(242, 242, 247)">
                    <img class="pics"src="{{ TextBubble.picture.url }}" alt="{{TextBubble.name}}">
                    </div>
                    <div class="words"
                         style="width: 60%;
                                max-width: 800px;
                                height: 400px;
                                float: right;
                                border-radius: 0px 5px 5px 0px;
                                border-left:5px solid rgb(209,209,214);
                                background: rgb(242, 242, 247)">
                        <h2 class="bTitle">
                            <svg class="bi bi-folder-plus" style="color: #5ca2d5" width="2em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M9.828 4H2.19a1 1 0 00-.996 1.09l.637 7a1 1 0 00.995.91H9v1H2.826a2 2 0 01-1.991-1.819l-.637-7a1.99 1.99 0 01.342-1.31L.5 3a2 2 0 012-2h3.672a2 2 0 011.414.586l.828.828A2 2 0 009.828 3h3.982a2 2 0 011.992 2.181L15.546 8H14.54l.265-2.91A1 1 0 0013.81 4H9.828zm-2.95-1.707L7.587 3H2.19c-.24 0-.47.042-.684.12L1.5 2.98a1 1 0 011-.98h3.672a1 1 0 01.707.293z" clip-rule="evenodd"/>
                                <path fill-rule="evenodd" d="M13.5 10a.5.5 0 01.5.5v2a.5.5 0 01-.5.5h-2a.5.5 0 010-1H13v-1.5a.5.5 0 01.5-.5z" clip-rule="evenodd"/>
                                <path fill-rule="evenodd" d="M13 12.5a.5.5 0 01.5-.5h2a.5.5 0 010 1H14v1.5a.5.5 0 01-1 0v-2z" clip-rule="evenodd"/>
                            </svg>
                            {{TextBubble.name}}
                        </h2>
                        <h6 class="bDate">{{TextBubble.pub_date}}</h6>
                        <h6 class="bText" style="color: rgb(72,72,74);">{{TextBubble.text}}</h6>
                        <ul class="lan" style="height: 10%; margin: 0 auto; float: bottom">
                            {% for Languages in TextBubble.llink.all %}
                            <li class="l">
                                <h6 class="lang" style="color: #f68887;">
                                    <svg class="bi bi-file-code" style="color: rgb(99, 99, 102);"width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M4 1h8a2 2 0 012 2v10a2 2 0 01-2 2H4a2 2 0 01-2-2V3a2 2 0 012-2zm0 1a1 1 0 00-1 1v10a1 1 0 001 1h8a1 1 0 001-1V3a1 1 0 00-1-1H4z" clip-rule="evenodd"/>
                                        <path fill-rule="evenodd" d="M8.646 5.646a.5.5 0 01.708 0l2 2a.5.5 0 010 .708l-2 2a.5.5 0 01-.708-.708L10.293 8 8.646 6.354a.5.5 0 010-.708zm-1.292 0a.5.5 0 00-.708 0l-2 2a.5.5 0 000 .708l2 2a.5.5 0 00.708-.708L5.707 8l1.647-1.646a.5.5 0 000-.708z" clip-rule="evenodd"/>
                                    </svg>
                                    {{Languages.languages}}</h6>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="space" style="height: 60px">
                </div>
                {% endfor %}
            </ul>
            <h3><a href="#top" class="top">Back to Top</a></h3>
        </div>
    </div>
</div>

</body>
</html>